### ISSUE TITLE
Disable after the reboot

### ISSUE THREAD

**Issue by chronoss09** [SilicaAndPina/RoActDat#1]
I test your program and it work but not after reboot

**Comment by hi1lol** [comment]
Do you use the Plugin or the App?

**Comment by chronoss09** [comment]
The app

**Comment by SilicaAndPina** [comment]
i did say the app was only until next reboot did i not?
for it to set it as read-only at boot, u must use the plugin + henkaku enso.

**Comment by chronoss09** [comment]
Ok thanks ;)

**Comment by SilicaAndPina** [comment]
is it really that hard to write ux0:tai/RoActDat.skprx into *KERNAL on config.txt?

**Comment by chronoss09** [comment]
No but it's *KERNEL not *KERNAL :)
